name: wingman
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  pin_code_fields: ^7.4.0
  flutter_bloc: ^8.1.3
  dio: ^5.1.2
  retrofit: ^4.0.1
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.1
  pretty_dio_logger: ^1.3.1
  libphonenumber: ^2.0.2
  country_code_picker: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.4
  json_serializable: ^6.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          style: italic
